# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_dhqIdpR2lbq8fLs_mMJHM4Uul7iOScC
"""

!pip install datasets

from datasets import load_dataset

dataset = load_dataset('arabic-generated-abstracts')

dataset = load_dataset("KFUPM-JRCAI/arabic-generated-abstracts")

print(dataset.keys())

dataset

print(dataset)

print(dataset.keys())

dataset = load_dataset("KFUPM-JRCAI/arabic-generated-abstracts")
print(dataset)

split = dataset["by_polishing"]

# View one sample
print(split[0])

from datasets import load_dataset

dataset = load_dataset("KFUPM-JRCAI/arabic-generated-abstracts")

print(dataset)
print(dataset.keys())

import pandas as pd

split = 'by_polishing'  # or 'from_title', 'from_title_and_content'
data = dataset[split]

# Convert to pandas DataFrame for easy manipulation
df = pd.DataFrame(data)

# Create a combined dataset with two columns: 'abstract' and 'label'
# We'll add rows for human and AI abstracts separately

human_df = pd.DataFrame({
    'abstract': df['original_abstract'],
    'label': 'human'
})

# Concatenate AI-generated abstracts from different columns with label 'ai'
ai_abstracts = pd.concat([
    df['allam_generated_abstract'],
    df['jais_generated_abstract'],
    df['llama_generated_abstract'],
    df['openai_generated_abstract']
], ignore_index=True)

ai_df = pd.DataFrame({
    'abstract': ai_abstracts,
    'label': 'ai'
})

# Combine human and AI data
combined_df = pd.concat([human_df, ai_df], ignore_index=True)

# Check distribution
print(combined_df['label'].value_counts())